"""Ensure Upload table schema is correct

Revision ID: 6cf8b2d8c6a9
Revises: afc123501224
Create Date: 2025-01-03 18:46:30.642714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf8b2d8c6a9'
down_revision = 'afc123501224'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.drop_column('file_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_name', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
