"""Add commission and net_premium to Upload

Revision ID: afc123501224
Revises: 56416a32525b
Create Date: 2025-01-03 17:59:07.020810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afc123501224'
down_revision = '56416a32525b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        batch_op.add_column(sa.Column('net_premium', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('commission', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('file_name', sa.String(length=255), nullable=True))
        # Explicitly name the foreign key constraint
        batch_op.create_foreign_key(
            'fk_upload_user',  # Name of the constraint
            'user',            # Referenced table
            ['user_id'],       # Local column
            ['id'],            # Referenced column
            ondelete='CASCADE'
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('upload', schema=None) as batch_op:
        # Drop the foreign key constraint by its explicit name
        batch_op.drop_constraint('fk_upload_user', type_='foreignkey')
        batch_op.drop_column('file_name')
        batch_op.drop_column('commission')
        batch_op.drop_column('net_premium')

    # ### end Alembic commands ###